import AppKit
import SwiftUI

/// Release previews are still frames. Opening a guide must never start a
/// process tap or request system audio recording permission.
enum GuideReleaseVisualKind: String, CaseIterable {
    case waveform38, overlay38, performanceFlexbar38
}

enum GuideFlexbarAsset {
    // Copied unchanged from Integrations/Flexbar/qa-output/karaoke-030.png,
    // generated by tools/qa.mjs with the shipping plugin Renderer.
    static var url: URL? {
        Bundle.module.url(forResource: "flexbar-karaoke-030", withExtension: "png", subdirectory: "GuideAssets")
    }
    static var image: NSImage? { url.flatMap(NSImage.init(contentsOf:)) }
}

struct GuideReleaseVisual: View {
    let kind: GuideReleaseVisualKind
    @Environment(\.colorScheme) private var colorScheme
    private var isLight: Bool { colorScheme == .light }

    var body: some View {
        VStack(spacing: 12) {
            switch kind {
            case .waveform38:
                waveformPreview
                Text("波形效果示意 · 固定频谱帧，不读取音频")
                    .font(.caption2).foregroundStyle(.secondary)
            case .overlay38:
                HStack(spacing: 8) {
                    overlaySongPreview
                    centeredLyricsPreview
                }
                Text("左：有波形歌卡  ·  右：关闭波形后的居中歌词")
                    .font(.caption2).foregroundStyle(.secondary)
            case .performanceFlexbar38:
                flexbarPreview
                Text("FlexDesigner 插件渲染示意 · 非硬件实拍")
                    .font(.caption2).foregroundStyle(.secondary)
            }
        }
        .padding(16)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background {
            LinearGradient(colors: isLight
                ? [Color(red: 0.88, green: 0.92, blue: 0.96), Color(red: 0.98, green: 0.89, blue: 0.85)]
                : [Color(red: 0.09, green: 0.17, blue: 0.27), Color(red: 0.27, green: 0.14, blue: 0.27)],
                startPoint: .topLeading, endPoint: .bottomTrailing)
        }
        .accessibilityElement(children: .contain)
        .accessibilityLabel(accessibilitySummary)
    }

    private var accessibilitySummary: String {
        switch kind {
        case .waveform38: "悬浮窗底部实时波形效果示意；此图是固定帧，不读取音频"
        case .overlay38: "左侧有波形歌曲信息卡，右侧是无波形时在玻璃中居中的歌词"
        case .performanceFlexbar38: "FlexDesigner 歌词插件实际渲染图片，非硬件实拍"
        }
    }

    private var waveformPreview: some View {
        VStack(spacing: 16) {
            HStack(spacing: 14) {
                demoCover.frame(width: 68, height: 68)
                VStack(alignment: .leading, spacing: 5) {
                    Text("让光随音乐流动").font(.system(size: 21, weight: .semibold))
                    Text("LyricsX Next · 演示歌曲").font(.callout).opacity(0.78)
                }
                Spacer(minLength: 0)
            }
            GuideWaveformCurve().frame(height: 18)
        }
        .foregroundStyle(.white)
        .padding(20)
        .frame(maxWidth: 470)
        .background(.black.opacity(isLight ? 0.72 : 0.48), in: .rect(cornerRadius: 22))
        .overlay { RoundedRectangle(cornerRadius: 22).strokeBorder(.white.opacity(0.22)) }
        .frame(maxHeight: .infinity)
    }

    private var overlaySongPreview: some View {
        VStack(spacing: 14) {
            HStack(spacing: 9) {
                demoCover.frame(width: 42, height: 42)
                VStack(alignment: .leading, spacing: 3) {
                    Text("让光随音乐流动").font(.caption.weight(.semibold)).lineLimit(2)
                        .fixedSize(horizontal: false, vertical: true)
                    Text("LyricsX Next").font(.caption2).lineLimit(1).minimumScaleFactor(0.8).opacity(0.75)
                }
                Spacer(minLength: 0)
            }
            GuideWaveformCurve().frame(height: 18)
        }
        .padding(.horizontal, 10).padding(.vertical, 14)
        .frame(maxWidth: .infinity, maxHeight: 140)
        .foregroundStyle(.white)
        .background(.black.opacity(isLight ? 0.76 : 0.5), in: .rect(cornerRadius: 18))
        .overlay { RoundedRectangle(cornerRadius: 18).strokeBorder(.white.opacity(0.25)) }
        .accessibilityLabel("开启波形：歌卡与波形保留均衡间距")
    }

    private var centeredLyricsPreview: some View {
        VStack(spacing: 0) {
            Text("LyricsX Next · 演示").font(.system(size: 9)).opacity(0.7)
                .frame(maxWidth: .infinity, alignment: .leading)
            Spacer(minLength: 0)
            VStack(spacing: 5) {
                Text("每一句，清楚呈现").font(.system(size: 17, weight: .semibold))
                Text("Lyrics stay centered").font(.caption2).opacity(0.7)
            }.frame(maxWidth: .infinity)
            Spacer(minLength: 0)
        }
        .padding(13)
        .frame(maxWidth: .infinity, maxHeight: 140)
        .foregroundStyle(.white)
        .background(.black.opacity(isLight ? 0.76 : 0.5), in: .rect(cornerRadius: 18))
        .overlay { RoundedRectangle(cornerRadius: 18).strokeBorder(.white.opacity(0.25)) }
        .accessibilityLabel("关闭波形：可见歌词在玻璃窗内居中")
    }

    private var flexbarPreview: some View {
        VStack(spacing: 16) {
            Text("Flexbar 歌词插件").font(.headline).frame(maxWidth: .infinity, alignment: .leading)
            if let image = GuideFlexbarAsset.image {
                Image(nsImage: image)
                    .interpolation(.high)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .frame(maxWidth: 720)
                    .accessibilityLabel("插件实际渲染的逐字歌词与翻译")
            } else {
                Text("插件效果图暂不可用").foregroundStyle(.secondary)
            }
            Text("设置 → 开发者选项 → Flexbar")
                .font(.caption).frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(18)
        .foregroundStyle(.white)
        .frame(maxWidth: 720)
        .background(Color(red: 0.035, green: 0.075, blue: 0.15), in: .rect(cornerRadius: 20))
        .frame(maxHeight: .infinity)
    }

    private var demoCover: some View {
        RoundedRectangle(cornerRadius: 9)
            .fill(LinearGradient(colors: [Color(red: 0.90, green: 0.42, blue: 0.53),
                                          Color(red: 0.31, green: 0.37, blue: 0.75)],
                                 startPoint: .topLeading, endPoint: .bottomTrailing))
            .overlay { Image(systemName: "music.note").foregroundStyle(.white.opacity(0.8)) }
    }
}

/// The same frequency order, amplitude mapping and quadratic contour as the
/// production NSView, fed one fixed illustrative frame without a capture worker.
struct GuideWaveformCurve: View {
    static let sampleBands: [Float] = [0.08, 0.12, 0.22, 0.34, 0.55, 0.67, 0.54, 0.42,
        0.31, 0.44, 0.61, 0.47, 0.33, 0.26, 0.38, 0.51, 0.41, 0.30,
        0.22, 0.28, 0.19, 0.12, 0.08, 0.05]
    var body: some View {
        GeometryReader { geometry in
            let points = OverlayWaveformGeometry.points(for: Self.sampleBands,
                width: geometry.size.width, height: geometry.size.height)
            let path = Path { path in
                guard let first = points.first, let last = points.last else { return }
                func flipped(_ point: CGPoint) -> CGPoint {
                    CGPoint(x: point.x, y: geometry.size.height - point.y)
                }
                path.move(to: flipped(first))
                for index in 1..<points.count {
                    let previous = points[index - 1], current = points[index]
                    let midpoint = CGPoint(x: (previous.x + current.x) / 2,
                        y: (previous.y + current.y) / 2)
                    path.addQuadCurve(to: flipped(midpoint), control: flipped(previous))
                }
                path.addQuadCurve(to: flipped(last), control: flipped(last))
            }
            path.stroke(.black.opacity(0.40), lineWidth: 2)
            path.stroke(.white, lineWidth: 1.5)
        }
        .mask {
            GeometryReader { geometry in
                LinearGradient(stops: zip(OverlayWaveformEdgeFade.locations(width: geometry.size.width),
                                          OverlayWaveformEdgeFade.alphas).map { location, alpha in
                    .init(color: .white.opacity(Double(alpha)), location: CGFloat(truncating: location))
                }, startPoint: .leading, endPoint: .trailing)
            }
        }
        .accessibilityHidden(true)
    }
}
